# Generated by Django 3.1.5 on 2021-05-13 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developer_test', '0004_auto_20210513_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RequestLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100, null=True)),
                ('response_code', models.PositiveSmallIntegerField()),
                ('method', models.CharField(max_length=10, null=True)),
                ('remote_address', models.CharField(max_length=20, null=True)),
                ('exec_time', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('body_response', models.TextField()),
                ('body_request', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
